version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  # api:
  #   build: ./api
  #   ports:
  #     - '3000:3000'
  keepwhitespaces:
    build: ./js-game-keep-white-space-b5d8b7d35857d4df4a3d85a9fa65aa4217e11757
    ports:
      - '4242:3000'
  behindasteroids:
    build: ./behind-asteroids-3ce49e995ffd50ff506ec010dd71257f0040f91a
    ports:
      - '4243:3000'
  js13K:
    build: ./js13k-2021-fd4b9e6e1954b8850125c0a7a0219db0607bf37e
    ports:
      - '4244:3000'
volumes:
  db:
    driver: local